apiVersion: apps/v1
kind: Deployment
metadata:
  name: suggestion-deployment
  namespace: upwind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: suggestion
  template:
    metadata:
      labels:
        app: suggestion
    spec:
      containers:
        - name: suggestion
          image: 841176797686.dkr.ecr.ap-south-1.amazonaws.com/upwind:IMAGE_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: suggestion-config
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: related-deployment
  namespace: upwind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: related
  template:
    metadata:
      labels:
        app: related
    spec:
      containers:
        - name: related
          image: 841176797686.dkr.ecr.ap-south-1.amazonaws.com/upwind:IMAGE_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          envFrom:
            - configMapRef:
                name: related-config
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multiagent-deployment
  namespace: upwind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multiagent
  template:
    metadata:
      labels:
        app: multiagent
    spec:
      containers:
        - name: multiagent
          image: 841176797686.dkr.ecr.ap-south-1.amazonaws.com/upwind:IMAGE_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 8002
          envFrom:
            - configMapRef:
                name: multiagent-config
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
